# Generated by Django 5.2.11 on 2026-02-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(help_text='UUID', max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='books/covers/')),
                ('pdf_file', models.FileField(upload_to='books/pdfs/')),
                ('file_size', models.CharField(blank=True, max_length=20, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('featured', models.BooleanField(default=False)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags', null=True)),
                ('uploaded_by', models.CharField(help_text='Firebase UID of admin', max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(help_text='Firebase UID', max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='student', max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('student_id', models.CharField(blank=True, help_text='Department-based ID like CSE001', max_length=50, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='id-proofs/')),
                ('id_proof_verified', models.BooleanField(default=False)),
                ('id_proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('id_proof_verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_proof_rejection_reason', models.TextField(blank=True, null=True)),
                ('id_proof_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.userprofile')),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
